# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/pub/signUp
Content-Type: application/json

{
    "id": "gs.won2",
    "password": "12341234",
    "nickName": "bluemirr5",
    "profileImg": "http://aaa.bb.cc/profile.jpg"
}

###

POST http://localhost:8080/pub/signin
Content-Type: application/json

{
    "id": "gs.won2",
    "password": "12341234"
}

###

POST http://localhost:8080/api/test
Authorization: Bearer ##로그인으로 반환된 토큰

###